# Generated by Django 4.2 on 2026-04-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_symbol', models.CharField(default='R', help_text='Currency symbol (e.g., $, €, R)', max_length=10)),
                ('currency_name', models.CharField(default='Rand', help_text='Full currency name', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
