# Generated by Django 4.2 on 2026-04-13 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_currency_symbol'),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_date', models.DateField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('total_deliveries', models.IntegerField(default=0)),
                ('completed_deliveries', models.IntegerField(default=0)),
                ('total_distance_km', models.DecimalField(blank=True, decimal_places=2, help_text='Total planned distance in km', max_digits=8, null=True)),
                ('estimated_duration_minutes', models.IntegerField(blank=True, help_text='Estimated time to complete route', null=True)),
                ('actual_duration_minutes', models.IntegerField(blank=True, help_text='Actual time taken to complete route', null=True)),
                ('actual_distance_km', models.DecimalField(blank=True, decimal_places=2, help_text='Actual distance traveled', max_digits=8, null=True)),
                ('start_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('start_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('end_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('end_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.deliveryvehicle')),
                ('delivery_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_routes', to='users.serviceagent')),
            ],
            options={
                'verbose_name': 'Delivery Route',
                'verbose_name_plural': 'Delivery Routes',
                'ordering': ['-route_date'],
            },
        ),
        migrations.CreateModel(
            name='RoutePlanningSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optimization_algorithm', models.CharField(choices=[('nearest_neighbor', 'Nearest Neighbor'), ('tsp', 'Traveling Salesman'), ('genetic', 'Genetic Algorithm'), ('custom', 'Custom')], default='nearest_neighbor', max_length=20)),
                ('max_deliveries_per_day', models.IntegerField(default=20)),
                ('max_route_duration_hours', models.DecimalField(decimal_places=1, default=8, max_digits=4)),
                ('max_weight_per_route', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('consider_time_windows', models.BooleanField(default=True)),
                ('consider_vehicle_capacity', models.BooleanField(default=True)),
                ('avoid_traffic', models.BooleanField(default=True)),
                ('prefer_faster_routes', models.BooleanField(default=True)),
                ('prefer_shorter_routes', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='route_planning_settings', to='users.serviceagent')),
            ],
            options={
                'verbose_name': 'Route Planning Setting',
                'verbose_name_plural': 'Route Planning Settings',
            },
        ),
        migrations.CreateModel(
            name='DeliveryLocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_address', models.CharField(blank=True, max_length=500, null=True)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, help_text='GPS accuracy in meters', max_digits=10, null=True)),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, help_text='Altitude in meters', max_digits=10, null=True)),
                ('speed', models.DecimalField(blank=True, decimal_places=2, help_text='Speed in km/h', max_digits=5, null=True)),
                ('bearing', models.DecimalField(blank=True, decimal_places=2, help_text='Direction in degrees', max_digits=5, null=True)),
                ('battery_percentage', models.IntegerField(blank=True, null=True)),
                ('signal_strength', models.IntegerField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='delivery.deliveryassignment')),
            ],
            options={
                'verbose_name': 'Delivery Location History',
                'verbose_name_plural': 'Delivery Location Histories',
                'ordering': ['recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(help_text='Order in the route (1, 2, 3, ...)')),
                ('destination_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_address', models.CharField(max_length=500)),
                ('destination_name', models.CharField(blank=True, max_length=255, null=True)),
                ('distance_from_previous_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estimated_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('service_time_minutes', models.IntegerField(blank=True, null=True)),
                ('actual_service_time_minutes', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reached', 'Reached'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_assignment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_stop', to='delivery.deliveryassignment')),
                ('delivery_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='delivery.deliveryroute')),
            ],
            options={
                'verbose_name': 'Route Stop',
                'verbose_name_plural': 'Route Stops',
                'ordering': ['delivery_route', 'sequence'],
                'unique_together': {('delivery_route', 'sequence')},
            },
        ),
        migrations.AddIndex(
            model_name='deliverylocationhistory',
            index=models.Index(fields=['delivery_assignment', 'recorded_at'], name='delivery_de_deliver_7acf37_idx'),
        ),
    ]
