# Generated by Django 4.2 on 2026-04-13 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_deliveryroute_routeplanningsetting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempControlPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_type', models.CharField(choices=[('frozen', 'Frozen (-18°C or below)'), ('refrigerated', 'Refrigerated (2-8°C)'), ('ambient', 'Ambient (15-25°C)'), ('dry', 'Dry Storage')], max_length=20, unique=True)),
                ('surcharge_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Percentage surcharge on base price', max_digits=5)),
                ('surcharge_fixed', models.DecimalField(decimal_places=2, default=0, help_text='Fixed amount surcharge', max_digits=10)),
                ('requires_vehicle_capability', models.BooleanField(default=True, help_text='Only available with temperature-controlled vehicles')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Temperature Control Pricing',
                'verbose_name_plural': 'Temperature Control Pricing',
            },
        ),
        migrations.CreateModel(
            name='WeightBasedPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_weight_kg', models.DecimalField(decimal_places=2, help_text='Minimum weight in kg for this surcharge', max_digits=10)),
                ('max_weight_kg', models.DecimalField(decimal_places=2, help_text='Maximum weight in kg. Use 999999 for unlimited', max_digits=10)),
                ('surcharge_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Percentage surcharge on base price', max_digits=5, verbose_name='Surcharge %')),
                ('surcharge_fixed', models.DecimalField(decimal_places=2, default=0, help_text='Fixed amount surcharge', max_digits=10)),
                ('applies_to_all_methods', models.BooleanField(default=True, help_text='If False, select specific delivery methods below')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_methods', models.ManyToManyField(blank=True, help_text='Select specific methods if not applying to all', related_name='weight_pricing', to='delivery.deliverymethod')),
            ],
            options={
                'verbose_name': 'Weight-Based Pricing',
                'verbose_name_plural': 'Weight-Based Pricing',
                'ordering': ['min_weight_kg'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price from pricing tier', max_digits=10)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, help_text='Delivery distance in km', max_digits=8, null=True)),
                ('distance_charge', models.DecimalField(decimal_places=2, default=0, help_text='Additional charge based on distance', max_digits=10)),
                ('actual_weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Actual weight of items', max_digits=10, null=True)),
                ('weight_surcharge', models.DecimalField(decimal_places=2, default=0, help_text='Surcharge for heavy items', max_digits=10)),
                ('temp_control_surcharge', models.DecimalField(decimal_places=2, default=0, help_text='Temperature control surcharge', max_digits=10)),
                ('signature_required_surcharge', models.DecimalField(decimal_places=2, default=0, help_text='Additional charge if signature required', max_digits=10)),
                ('rush_delivery_surcharge', models.DecimalField(decimal_places=2, default=0, help_text='Rush/urgent delivery surcharge', max_digits=10)),
                ('other_surcharges', models.DecimalField(decimal_places=2, default=0, help_text='Any other additional charges', max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Percentage discount', max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Fixed amount discount', max_digits=10)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Tax percentage', max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='Calculated tax amount', max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Total before tax', max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, help_text='Total delivery cost including tax', max_digits=10)),
                ('currency', models.CharField(default='ZAR', max_length=3)),
                ('notes', models.TextField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost_breakdown', to='delivery.orderdelivery')),
            ],
            options={
                'verbose_name': 'Delivery Cost',
                'verbose_name_plural': 'Delivery Costs',
            },
        ),
        migrations.CreateModel(
            name='DeliveryPricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_unit', models.CharField(choices=[('km', 'Kilometers'), ('miles', 'Miles')], default='km', max_length=10)),
                ('min_distance', models.DecimalField(decimal_places=2, help_text='Minimum distance for this tier', max_digits=8)),
                ('max_distance', models.DecimalField(decimal_places=2, help_text='Maximum distance for this tier. Use 999999 for unlimited', max_digits=8)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price for this distance tier', max_digits=10)),
                ('price_per_unit_distance', models.DecimalField(decimal_places=2, help_text='Additional cost per km/mile', max_digits=8)),
                ('price_per_kg', models.DecimalField(decimal_places=2, default=0, help_text='Additional cost per kilogram (optional)', max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_tiers', to='delivery.deliverymethod')),
            ],
            options={
                'verbose_name': 'Delivery Pricing Tier',
                'verbose_name_plural': 'Delivery Pricing Tiers',
                'ordering': ['delivery_method', 'min_distance'],
                'unique_together': {('delivery_method', 'min_distance', 'max_distance')},
            },
        ),
    ]
