# Generated by Django 4.2 on 2026-04-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_tempcontrolpricing_weightbasedpricing_deliverycost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdelivery',
            name='delivery_distance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distance in kilometers from store to delivery address', max_digits=10, null=True),
        ),
    ]
