# Generated by Django 4.2 on 2026-04-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='currency_symbol',
            field=models.CharField(default='R', help_text='Preferred currency symbol (e.g., $, €, R)', max_length=10),
        ),
    ]
