# Generated by Django 4.2 on 2026-04-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_currency_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bank_account_holder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bank_account_type',
            field=models.CharField(blank=True, choices=[('savings', 'Savings Account'), ('checking', 'Cheque Account'), ('business', 'Business Account'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bank_branch_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
