# Generated by Django 4.2 on 2026-04-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_bank_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketagent',
            name='certifications',
            field=models.TextField(blank=True, help_text='e.g., SAPO Organic, Fair Trade, Rainforest Alliance, etc.', null=True),
        ),
        migrations.AddField(
            model_name='marketagent',
            name='farm_description',
            field=models.TextField(blank=True, help_text='Detailed description of farm practices, what you grow, etc.', null=True),
        ),
        migrations.AddField(
            model_name='marketagent',
            name='is_gmo_free',
            field=models.BooleanField(default=False, help_text='Are products GMO-free?'),
        ),
        migrations.AddField(
            model_name='marketagent',
            name='is_organic',
            field=models.BooleanField(default=False, help_text='Is this farm certified organic?'),
        ),
    ]
