# Generated by Django 4.2 on 2026-04-11 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbalance',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billingtransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_transactions', to='orders.order'),
        ),
        migrations.AddField(
            model_name='billingtransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminbilling',
            name='billing_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.billingplan'),
        ),
        migrations.AddField(
            model_name='adminbilling',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_billings', to=settings.AUTH_USER_MODEL),
        ),
    ]
