# Generated by Django 4.2 on 2026-04-12 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_currency_symbol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_order_is_paid_order_paid_at_order_payment_verified_and_more'),
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Order In Business Account', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_balance', models.DecimalField(decimal_places=2, default=0, help_text='Total balance in business account', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('subscriber_deposit', 'Subscriber Deposit (Money In)'), ('subscriber_purchase', 'Subscriber Purchase (Money Out)'), ('market_agent_payout', 'Market Agent Payout (Money Out)'), ('service_agent_payout', 'Service Agent Payout (Money Out)'), ('refund', 'Refund (Money Out)'), ('admin_fee', 'Admin Fee (Money In)'), ('adjustment', 'Adjustment')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_id', models.CharField(blank=True, help_text='External reference (payment gateway ID, order ID, etc.)', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='billing.businessaccount')),
                ('market_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_transactions_as_market_agent', to='users.marketagent')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_transactions', to='orders.order')),
                ('service_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_transactions_as_service_agent', to='users.serviceagent')),
                ('subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_transactions_as_subscriber', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
