# Generated by Django 4.2 on 2026-04-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_payoutrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminFeeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('fixed', 'Fixed Monthly Amount'), ('percentage', 'Percentage of Sales')], default='percentage', max_length=20)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly fixed fee amount (e.g., 500.00 Rand)', max_digits=12, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Percentage of sales (e.g., 5 for 5%)', max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Admin Fee Config',
            },
        ),
    ]
