# Generated by Django 4.2 on 2026-04-11 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprice',
            name='service_agent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_price', to='users.serviceagent'),
        ),
        migrations.AddField(
            model_name='serviceavailability',
            name='service_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='users.serviceagent'),
        ),
        migrations.AlterUniqueTogether(
            name='serviceavailability',
            unique_together={('service_agent', 'day_of_week', 'start_time', 'end_time')},
        ),
    ]
