# Generated by Django 4.2 on 2026-04-11 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='market_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.marketagent'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('market_agent', 'sku')},
        ),
    ]
