# Generated by Django 4.2 on 2026-04-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='certifications',
            field=models.CharField(blank=True, help_text='e.g., SAPO Organic, Fair Trade, etc.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_gmo_free',
            field=models.BooleanField(default=False, help_text='Is this product GMO-free?'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_organic',
            field=models.BooleanField(default=False, help_text='Is this product certified organic?'),
        ),
    ]
